feat: General improvements
milharal-dev/nemli-nemlerei-bot pull request #14
Opened 2024-07-23 22:12 UTC by rdenadai

- Removing stopwords from prompt for OpenAI bot

2024-07-23 22:16 UTC, mattpsvreis requested changes
Roda um `pdm format` e dá um push por favor :)

2024-07-23 22:40 UTC, mattpsvreis approved these changes
LGTM!

2024-07-23 23:18 UTC, ryukinix commented
Pode resolver os conflitos fazendo rebase @rdenadai ?

2024-07-23 23:33 UTC, ryukinix commented on nemli/nlp/messages.py
> +from nltk.corpus import stopwords
Não precisa fazer download antes de usar?

2024-07-23 23:45 UTC, ryukinix commented on tests/test_stopwords.py
> +import pytest
Esse teste passa rodando `pdm tests` ?

2024-07-24 00:02 UTC, rdenadai commented on tests/test_stopwords.py
> +import pytest
Com cerveja

2024-07-24 00:04 UTC, rdenadai commented on tests/test_stopwords.py
> +import pytest
![image](https://github.com/user-attachments/assets/9bba5f49-ffa5-4d6a-b31c-550a0a126e34)

2024-07-24 00:10 UTC, rdenadai commented on nemli/nlp/messages.py
> +from nltk.corpus import stopwords
Uhm ... sim precisa...

```python
import nltk

nltk.download('stopwords')
```

2024-07-24 00:11 UTC, rdenadai commented on nemli/nlp/messages.py
> +from nltk.corpus import stopwords
Vou add isso no README.md

2024-07-24 00:13 UTC, rdenadai commented on nemli/nlp/messages.py
> +from nltk.corpus import stopwords
Added essa info no README.md

2024-07-24 01:34 UTC, ryukinix requested changes
Alguns detalhes

2024-07-24 01:34 UTC, ryukinix commented on tests/test_stopwords.py
> +import pytest
@flipbit03 a gente precisa de um CI básico rodando o que é coberto pelo `pdm check` (mypy, flake8, pytest)

2024-07-24 01:34 UTC, ryukinix commented on nemli/config.py
> +    openai_model: str
Fico pensando senão seria mais fácil deixar o default aqui @rdenadai 

Invés do env template. 
Eu acho mais fácil manter o default aqui do que lá no arquivo.

Igual você deixou ali as mensagens, com 100, acho que fica melhor. 

Toda vez que atualizar o template vou ter que fazer cópia manual etc. acho que não é muito produtivo, nem muito visível 

@rdenadai

2024-07-24 01:34 UTC, ryukinix commented on nemli/nlp/messages.py
> +from nltk.corpus import stopwords
Automatizado tbm

2024-07-24 01:38 UTC, rdenadai commented on nemli/config.py
> +    openai_model: str
Não vejo problemas ... vou deixar como default aqui o modelo do chatgpt-4o-mini

2024-07-24 01:43 UTC, rdenadai commented on nemli/nlp/messages.py
> +from nltk.corpus import stopwords
Added aqui
https://github.com/milharal-dev/nemli-nemlerei-bot/pull/14/files#diff-f6ea80815a154863a734aa82fa0e23a5db474cc156068092b7fd13310a4565beR47

2024-07-24 01:44 UTC, rdenadai commented on tests/test_stopwords.py
> +import pytest
`pdm check` ok tb

![image](https://github.com/user-attachments/assets/83b8949b-fb8b-42e4-9f5e-7d875d860020)

2024-07-24 02:07 UTC, ryukinix approved these changes
LGTM

2024-07-24 02:08 UTC, merged